[project]
name = "file-sort"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Simon Chapman", email = "schapman14663@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
file-sort = "file_sort:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
